### ISSUE TITLE
XML tags with attribute and values issue

### ISSUE THREAD

**Issue by mehdi262** [minchulkim87/pandas_read_xml#10]
Hi guys, I have another use case, which I have the solution as well. want your feedback on the issue and the solution.
Usecase: There is a case that an XML tag sometimes  has attribute and sometimes not. If an XML tags has value and attribute the xmltodict.parse, parse it as a dictionary. As a result, using the updated code from the previouse issue, the following XML content flattened to the shown dataframe .
```
xml ='''<main>
        <a> <b>test</b></a>
        <a> <b>test</b></a>
        <a> <b xsi:nil="true" /></a>
        <a> <b xsi:nil="false">testValue</b></a>
        </main>
    '''
```
![image](https://user-images.githubusercontent.com/27056828/113931878-d8f1f400-97a7-11eb-91c0-5f67b170575d.png)

Actually the column **b** and **b|#text** are the same and must be named as **b**.
to solve the problem I suggest following changes. If you think this is a valid fix let me know to create the pull request.

```
def normalise(df: pd.DataFrame, column: str) -> pd.DataFrame:
    df = df.reset_index(drop=True).join(json_normalize(df[column], sep='|', max_level=0).add_prefix(str(column)+'|'))
    text_col = column+'|#text'
    if text_col in df.columns:         
        df[column] = df[text_col]
        df=df.drop(columns=text_col)
    else:
        df = df.drop(columns=[column])
    return (df)


    def mixed_normalise(df: pd.DataFrame, column: str) -> pd.DataFrame:
    normalisable = df[column].apply(lambda x: (type(x)==dict) | (type(x)==collections.OrderedDict))
    if df.loc[~normalisable, column].isna().all():
        return pd.concat([df.loc[normalisable, :].pipe(normalise, column),
                          df.loc[~normalisable, :]],
                         sort=True,
                         join='outer').drop(columns=[column]).reset_index(drop=True)
    else:
        t_df = pd.concat([df.loc[normalisable, :].pipe(normalise, column),
                          df.loc[~normalisable, :]],
                         sort=True,
                         join='outer').reset_index(drop=True)
        print(t_df.loc[normalisable].columns)
        for col in t_df.loc[normalisable].columns:
            text_col = str(col)+'|#text'
            if text_col in t_df.loc[normalisable].columns:
                t_df[col] = t_df[[col,text_col]].apply(lambda x: ','.join(x.astype(str)),axis=1)
                t_df= t_df.drop(columns=text_col,axis=1)

        return t_df
```
execution result:
![image](https://user-images.githubusercontent.com/27056828/113932913-d348de00-97a8-11eb-8cba-6842969a4212.png)

Please let me know your feedbacks.

**Comment by minchulkim87** [comment]
Done. Didn't want to introduce the if statement. But I think column|#text being renamed back to the original column tag name is appropriate. This will break any existing pipeline that uses column|#text though... So... had to version bump yet again.

**Comment by mehdi262** [comment]
Great. Thanks
