### ISSUE TITLE
Not able get the data into dataframe

### ISSUE THREAD

**Issue by krishna3008** [minchulkim87/pandas_read_xml#11]
I have a xml as
data = '''<reportApi _class="io.jenkins.plugins.analysis.core.restapi.ReportApi">
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
INSTCAN_If.c
</fileName>
<fingerprint>687664561F81612CBCA94ADFB6F5B1CB</fingerprint>
<lineEnd>14576</lineEnd>
<lineStart>14576</lineStart>
<message>
possible truncation at implicit conversion to type "unsigned short int"
</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>83</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
NSTCAN_If.c
</fileName>
<fingerprint>AEABFA4F241E45F46F6575C00A124290</fingerprint>
<lineEnd>16933</lineEnd>
<lineStart>16933</lineStart>
<message>missing braces around initializer</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>accm_unblock.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
ccm_unblock.c
</fileName>
<fingerprint>B216BBDDDB75B065A1933B237B15BA3B</fingerprint>
<lineEnd>331</lineEnd>
<lineStart>331</lineStart>
<message>side effects of 'sizeof' operand are ignored</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<size>400</size>
</reportApi>'''

And I used the library to parse and got the entire files in the single row 

![image](https://user-images.githubusercontent.com/74471606/119497653-774f0e80-bd82-11eb-8afd-788366f2cd02.png)

I have previously used the same code a while back and I have seen library is updated 
Ref the image and please help me if anything I have missed

**Comment by minchulkim87** [comment]
Hi
Could you use the code formatting? I don't see the XML.

**Comment by krishna3008** [comment]
Actually I reading the xml data from a Jenkins xml using data = requests.get(url).text
I have provide the data which I got as output

**Comment by krishna3008** [comment]
Previously I have used the same format 3 months back 
there it is extracting good
I have used this in a new machine with new version 
I am seeing these problem

**Comment by minchulkim87** [comment]
Okay. I get that. I am just not seeing the xml. Could you put the markdown syntax so that the xml displays as it is?

**Comment by minchulkim87** [comment]
Triple back ticks (```) to indicate code.

```
<tag>something</tag>
```

But not

<tag>something</tag>

Otherwise the tags don't display.

In the meantime, the only "breaking" changes that I can think of were: `root_is_rows=False`

```python
pdx.read_xml(data, root_key_list, root_is_rows=False)
```

perhaps.

**Comment by krishna3008** [comment]
`data = '''<reportApi _class="io.jenkins.plugins.analysis.core.restapi.ReportApi">
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
C:/jenkins/workspace/FCA_WL_CADM/FCA_WL_CADM_MAP/CADM_MAP/build/build_files/aptiv_specific/output/WL/A_APP/allsrc/CtAp_INSTCAN_If.c
</fileName>
<fingerprint>687664561F81612CBCA94ADFB6F5B1CB</fingerprint>
<lineEnd>14576</lineEnd>
<lineStart>14576</lineStart>
<message>
possible truncation at implicit conversion to type "unsigned short int"
</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>83</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
C:/jenkins/workspace/FCA_WL_CADM/FCA_WL_CADM_MAP/CADM_MAP/build/build_files/aptiv_specific/output/WL/A_APP/allsrc/CtAp_INSTCAN_If.c
</fileName>
<fingerprint>AEABFA4F241E45F46F6575C00A124290</fingerprint>
<lineEnd>16933</lineEnd>
<lineStart>16933</lineStart>
<message>missing braces around initializer</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>accm_unblock.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
C:/jenkins/workspace/FCA_WL_CADM/FCA_WL_CADM_MAP/CADM_MAP/build/build_files/aptiv_specific/output/WL/A_APP/allsrc/accm_unblock.c
</fileName>
<fingerprint>B216BBDDDB75B065A1933B237B15BA3B</fingerprint>
<lineEnd>331</lineEnd>
<lineStart>331</lineStart>
<message>side effects of 'sizeof' operand are ignored</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<size>400</size>
</reportApi>'''

df = pdx.read_xml(data, root_key_list=['reportApi', 'issue'])
print(df)`

**Comment by krishna3008** [comment]
```data = '''<reportApi _class="io.jenkins.plugins.analysis.core.restapi.ReportApi">
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
_INSTCAN_If.c
</fileName>
<fingerprint>687664561F81612CBCA94ADFB6F5B1CB</fingerprint>
<lineEnd>14576</lineEnd>
<lineStart>14576</lineStart>
<message>
possible truncation at implicit conversion to type "unsigned short int"
</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>83</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
Ap_INSTCAN_If.c
</fileName>
<fingerprint>AEABFA4F241E45F46F6575C00A124290</fingerprint>
<lineEnd>16933</lineEnd>
<lineStart>16933</lineStart>
<message>missing braces around initializer</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>accm_unblock.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
ccm_unblock.c
</fileName>
<fingerprint>B216BBDDDB75B065A1933B237B15BA3B</fingerprint>
<lineEnd>331</lineEnd>
<lineStart>331</lineStart>
<message>side effects of 'sizeof' operand are ignored</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<size>400</size>
</reportApi>'''
df = pdx.read_xml(data, root_key_list=['reportApi', 'issue'])
print(df)```

**Comment by minchulkim87** [comment]
Hi,

so I have tested using

```python
import pandas_read_xml as pdx

data = '''<reportApi>
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
_INSTCAN_If.c
</fileName>
<fingerprint>687664561F81612CBCA94ADFB6F5B1CB</fingerprint>
<lineEnd>14576</lineEnd>
<lineStart>14576</lineStart>
<message>
possible truncation at implicit conversion to type "unsigned short int"
</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>83</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>CtAp_INSTCAN_If.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
Ap_INSTCAN_If.c
</fileName>
<fingerprint>AEABFA4F241E45F46F6575C00A124290</fingerprint>
<lineEnd>16933</lineEnd>
<lineStart>16933</lineStart>
<message>missing braces around initializer</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<issue>
<baseName>accm_unblock.c</baseName>
<category>Warning</category>
<columnEnd>0</columnEnd>
<columnStart>0</columnStart>
<description/>
<fileName>
ccm_unblock.c
</fileName>
<fingerprint>B216BBDDDB75B065A1933B237B15BA3B</fingerprint>
<lineEnd>331</lineEnd>
<lineStart>331</lineStart>
<message>side effects of 'sizeof' operand are ignored</message>
<moduleName/>
<origin>tasking-vx</origin>
<packageName>-</packageName>
<reference>69</reference>
<severity>NORMAL</severity>
<type>-</type>
</issue>
<size>400</size>
</reportApi>'''
df = pdx.read_xml(data, root_key_list=['reportApi', 'issue'], root_is_rows=False)
df
```

Which seems to work.

**Comment by krishna3008** [comment]
Yeah it's working for the basic function
I will try with my core function and update if any errors 
Thanks
