### ISSUE TITLE
Breaking change of flatten

### ISSUE THREAD

**Issue by rjschmitt** [minchulkim87/pandas_read_xml#13]
I just saw, that you progressed to version 0.3.1. Thank you for the active development. Unfortunately, starting from 0.2.0 `flatten` breaking changed. If there were version tags in the git repo, one could retrace the change.

Also a Changelog would help us to decide if an update is worth the effort of digging into this or just staying with the old version.

Kind regards,
Raphael

**Comment by minchulkim87** [comment]
Thanks.
Sorry about that. This was quite a poorly planned packaging/development on my part.
I really only intended this to be a temporary solution until the pandas team (who are really amazing with this sort of stuff) created a read xml method. Their next version release will include such a method. So hopefully this tool can truly become obsolete.

Although the flattening part of the module isn't really an XML thing... pandas already has json normalize and explode methods.

Any suggestions on how to clean this mess up? I am 1. not very experienced with this stuff, 2. time poor.

**Comment by rjschmitt** [comment]
First of all, I thank you for the fast reply!
I found out how the behavior changed. We just had to apply `flatten` two times in order to get the old behavior.
To be honest, the new behavior is more consistent - thanks for improving that. I would suggest you to just add some Changelog in future. It's just helping devs to understand the progress. Other projects realize that with a CHANGELOG.md inside their repo. Further, I would suggest you to add a version tag in the git repo in future. I wouldn't care about the past stuff anymore, but maybe change it in future. [Here](https://github.com/raphiniert-com/ra-data-postgrest) you can see an example, how this can be done.

And although pandas plans a read_xml, I did'nt find any information, when it will be released! I very like your project! Thanks for realizing and publishing this handsome project!
