### ISSUE TITLE
UnicodeDecodeError when reading XML with Unicode chatacters

### ISSUE THREAD

**Issue by jcalvarezj** [minchulkim87/pandas_read_xml#6]
Hello, I am presenting the following problem: when I try to load an XML file with special unicode characters I get an UnicodeDecodeError. Here is the Stack Trace:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-10-fd51444ff71f> in <module>
----> 1 places_df = pdx.read_xml(DATA_FOLDER + DATASET_1_FILE_1, ['places', 'place'])
      2 places_df

c:\Users\ASUS Q550.000\Documents\Aprendizaje\Repositorios\estaciones\venv\lib\site-packages\pandas_read_xml.py in read_xml(path_or_xml, root_key_list, transpose)
    104                     return read_xml_files_in_double_zip_as_dataframe(zf, root_key_list, transpose=transpose)
    105         elif path_or_xml.endswith('.xml'):
--> 106             return read_xml_as_dataframe(read_xml_from_path(path_or_xml), root_key_list)
    107         else:
    108             return read_xml_as_dataframe(path_or_xml, root_key_list)

c:\Users\ASUS Q550.000\Documents\Aprendizaje\Repositorios\estaciones\venv\lib\site-packages\pandas_read_xml.py in read_xml_from_path(path)
     52 def read_xml_from_path(path: str) -> str:
     53     with open(path, 'r') as xf:
---> 54         return xf.read()
     55 
     56 

c:\python367\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 73419: character maps to <undefined>
---------------------------------------------------------------------------
```

I was wondering if an idea of a solution was to add an encoding option in the  **with open(...)** statement of the **read_xml_from_path** function, so that it is possible to work with other file encodings such as UTF-8 (and adding an optional encoding arguments for that function and **read_xml**)

The dataset I was trying to load is this one: https://publicacionexterna.azurewebsites.net/publicaciones/places, which is in UTF-8 encoding.

My system is Windows 10 with Python 3.6.7

Thank you for your attention.

**Comment by minchulkim87** [comment]
Hi

Sorry for the delay in response.
I loaded the data without problem and am unable to reproduce the error.
Python by default uses the same encoding used by the environment you run it in. I suspect that the python environment you are working with is not using utf-8 or compatible encoding.
Having said that, I added the optional argument to pass encoding (bumped to version 0.0.8)

Thank you
