### ISSUE TITLE
Issue with tags that sometimes have value and sometimes is a single close tag with an attribute

### ISSUE THREAD

**Issue by mehdi262** [minchulkim87/pandas_read_xml#9]
Hi everyone,
It is amazing. But, I have hard time flattening a XML file that has a tag which sometime has value and sometime doesn't have value and instead has a single tag and an attribute.

my code:
```
def get_to_root_in_dict(the_dict: dict, root_key_list: Optional[List[str]]=None) -> dict:
    '''This is an overraiding of the same funciton from pandas_read_xml. '''
    if not root_key_list:
        return the_dict
    elif len(root_key_list) > 1:
        return get_to_root_in_dict(the_dict[root_key_list[0]], root_key_list[1:])
    else:
        return the_dict[root_key_list[0]] if root_key_list[0] in the_dict.keys() else None
        # return the_dict[root_key_list[0]]


xml ='''<main>
        <a> <b>test</b></a>
        <a> <b>test</b></a>
        <a> <b xsi:nil="true" /></a>
        </main>
    '''

xml_dict = xmltodict.parse(xml, force_list='a')
df = pd.DataFrame(get_to_root_in_dict(xml_dict, ['main','a']))         
if not df.empty:             
    for i in range(0,2):
        df = flatten(df)
print(df.columns)
print(df.head())
```
output:
![image](https://user-images.githubusercontent.com/27056828/113344859-810a4780-92e6-11eb-8ea9-98ccaa4f0ac6.png)
I would like to get this reuslt:
![image](https://user-images.githubusercontent.com/27056828/113345209-ff66e980-92e6-11eb-8ebc-1f8b46266878.png)
or at least:
![image](https://user-images.githubusercontent.com/27056828/113345285-1ad1f480-92e7-11eb-9d53-87be88726777.png)

**Comment by minchulkim87** [comment]
Hey, Thanks for using and providing comments.

While I'd love to solve this issue, I think this package is coming to the end of its intended lifespan.
Pandas is going to release a `pd.read_xml()` way of reading XML files. And they would have done a proper job of doing so too.

You can see (and probably start using) the [dev documents here](https://pandas.pydata.org/docs/dev/reference/api/pandas.read_xml.html).

If you do continue to use this, and have found a way to fix it, I'd be happy to accept a pull request. But in any case, as soon as the pandas 1.3 is release, I will make a note in the readme to redirect anybody who finds this github and probably archive this.

**Comment by bjornjorgensen** [comment]
pd.read_xml() only works on XPATH levels, so if you have a very nested xml file it wont work.

**Comment by minchulkim87** [comment]
Okay. So I may have found what is potentially a bug in my original code.

Basically, a part of what pandas_read_xml does to flatten is to determine which flattening action should be taken, then apply that flattening action. This is in part because the json_normalize in pandas is inadequate for the weirdness of XML structure.

Anyway, long story short, I think this particular function in pandas_read_xml:

```python
def mixed_normalise(df: pd.DataFrame, column: str) -> pd.DataFrame:
    normalisable = df[column].apply(lambda x: (type(x)==dict) | (type(x)==collections.OrderedDict))
    return pd.concat([df.loc[normalisable, :].pipe(normalise, column),
                      df.loc[~normalisable, :]],
                     sort=True,
                     join='outer').drop(columns=[column]).reset_index(drop=True)
```

Should be:

```python
def mixed_normalise(df: pd.DataFrame, column: str) -> pd.DataFrame:
    normalisable = df[column].apply(lambda x: (type(x)==dict) | (type(x)==collections.OrderedDict))
    if df.loc[~normalisable, column].isna().all():
        return pd.concat([df.loc[normalisable, :].pipe(normalise, column),
                          df.loc[~normalisable, :]],
                         sort=True,
                         join='outer').drop(columns=[column]).reset_index(drop=True)
    else:
        return pd.concat([df.loc[normalisable, :].pipe(normalise, column),
                          df.loc[~normalisable, :]],
                         sort=True,
                         join='outer').reset_index(drop=True)
```

I'll make the changes and bump the version. @mehdi262 Could you try re-installing and see if it fixes the issue?

**Comment by minchulkim87** [comment]
@bjornjorgensen Does it mean... do you wish I continue maintaining this package until pandas enhances its pd.read_xml() to work with nested XML?

**Comment by mehdi262** [comment]
Hi @minchulkim87, Thanks for spending time on this issue. I would suggest, maintaining the package until it the panda.read_xml get mature enough. I found your work valuable. Iwas working on the issue parallelly. Sure, I will check my use case and let you know the result.

**Comment by mehdi262** [comment]
Your suggested change solved. Appreciate it.
